-- Run this file in Supabase: SQL Editor > New query.

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  location text not null,
  price numeric not null,
  bedrooms integer not null,
  bathrooms integer not null,
  area_sqft integer not null,
  property_type text not null check (property_type in ('family', 'apartment', 'waterfront', 'investment', 'luxury')),
  image_url text not null,
  description text not null,
  status text not null default 'available' check (status in ('available', 'under_offer', 'sold')),
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  service text,
  location_preference text,
  message text,
  source_page text,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.properties enable row level security;
alter table public.inquiries enable row level security;
alter table public.profiles enable row level security;

create policy "Public can view available properties"
on public.properties for select
using (status = 'available');

create policy "Admins can manage properties"
on public.properties for all
to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true))
with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));

create policy "Anyone can submit an inquiry"
on public.inquiries for insert
with check (true);

create policy "Admins can view inquiries"
on public.inquiries for select
to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));

create policy "Users can view their own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

-- Optional starter content. Run after creating the tables.
insert into public.properties
  (title, slug, location, price, bedrooms, bathrooms, area_sqft, property_type, image_url, description, featured)
values
  ('Maple Grove House', 'maple-grove-house', 'Westview', 845000, 4, 3, 2760, 'family', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', 'Family-oriented detached home with strong local demand, renovated interiors, and mature landscaping.', false),
  ('Seabrook Contemporary', 'seabrook-contemporary', 'Harbor Point', 1240000, 5, 4, 3980, 'waterfront', 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80', 'Design-led premium residence with scale, daylight, and strong long-term appeal in a prime location.', true),
  ('Parkline Apartment', 'parkline-apartment', 'Central District', 620000, 2, 2, 1420, 'apartment', 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', 'Central apartment with clean specifications, commuter convenience, and resilient rental positioning.', false)
on conflict (slug) do nothing;
